"""Project-wide constants."""

PITCH_LENGTH_M = 105.0
PITCH_WIDTH_M = 68.0
PITCH_CENTER_X_M = PITCH_LENGTH_M / 2.0
PITCH_CENTER_Y_M = PITCH_WIDTH_M / 2.0

DATASET_METRICA = "metrica"
DATASET_SKILLCORNER = "skillcorner"
DATASET_SOCCERTRACK = "soccertrack"
DATASET_STATSBOMB = "statsbomb"
DATASET_SYNTHETIC = "synthetic"

AGENT_PLAYER = "player"
AGENT_BALL = "ball"
AGENT_REFEREE = "referee"
AGENT_UNKNOWN = "unknown"
AGENT_TYPES = {AGENT_PLAYER, AGENT_BALL, AGENT_REFEREE, AGENT_UNKNOWN}

PLAYER_SPEED_WARNING_MPS = 12.0
BALL_SPEED_WARNING_MPS = 40.0

